# Generated by Django 3.1.4 on 2021-02-07 16:48

import autoslug.fields
import book.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210206_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=book.models.slug, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
