# Generated by Django 3.1.4 on 2021-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210207_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='front',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/books'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/books'),
        ),
    ]
